### ISSUE TITLE
Move to microsoft/PowerToys

### ISSUE THREAD

**Issue by bricelam** [bricelam/ImageResizer#146]
Mission accomplished. Microsoft is reviving the [Windows PowerToys](https://github.com/microsoft/PowerToys) and we're going to be a part of it.

### To Do

- [x] Fix a few issues
  - [x] Migrate config after version bumps #103
  - [x] Allow directories in the filename template #118 (if trivial)
  - [x] ~~Preserve modified date when resizing originals~~ #145
- [x] Add TODO comments for a few enhancements
  - [x] Option to remove metadata #3
  - [x] Detect WIC codecs in the shell extension #7
  - [x] Allow command-line arguments to skip the input page #14
  - [x] Add UI to reorder the default sizes #15
  - [x] Enhance the UX of specifying **Resize the original pictures** when resizing into a different directory #88
  - [x] Document the advantages the Windows.Graphics.Imaging async APIs would provide
- [x] Update translations
- [x] Release a final 3.1.2 version
- [x] Re-license under the MIT license
- [x] Submit a PR to [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
- [x] Archive this repo
  - [x] Update README saying we moved
  - [x] Close issues forwarding users to microsoft/PowerToys
  - [x] Archive repo (makes it read-only)
- [x] Make POEditor project private
- [x] Write a blog post
  - [x] Say we moved
  - [x] Link to final "bricelam" release
  - [x] (optional) Retell the history of the project
- [x] Redirect https://bricelam.net/ImageResizer to the blog post

cc @crutkas

**Comment by JNavas2** [comment]
![unnamed](https://user-images.githubusercontent.com/14850792/71311991-c8fba880-23da-11ea-998e-16d7eb7eb367.gif)

**Comment by JNavas2** [comment]
**BUT**: "Note: in order to run PowerToys,
you'll need to be running at least Windows build 17134 or higher."

**That leaves out those of us on Windows 8/8.1 (not to mention Windows 7 holdouts),
so please please do NOT kill this project!**

**Comment by bricelam** [comment]
All the existing releases and source code and will continue to be available in this repo.

I expect the initial enhancements they’ll take on are:

1. Refresh the UI to incorporate Fluent design principles. They probably want to leverage a technology like WinUI to help accomplish this.

2. Using a modern deployment technology like MSIX for enhanced security and serviceability.

There is some support for these technologies on Windows 7, but it is limited. The cost of creating modern software on legacy platforms goes up every year while the benefits go down. I don’t blame them for only targeting modern versions of Windows.

I can’t imagine them adding many new features to the utility. I think has evolved to the full extent it can without it taking on additional responsibilities not related to resizing images. In other words, if you stay on the current release, I don’t think you’ll be missing out on anything significant. But I’ll certainly keep an eye on things and if there’s enough demand for a new release with down-level support, I’m happy to help make that happen.

 P.S. Have you tried WSL2 support in Windows 10? Running Ubuntu natively inside of Windows 10 is a dream come true—no VMs, containers, or software layers (like MinGW), just a Linux kernel running side-by-side with the Windows kernel.

**Comment by JNavas2** [comment]
> There is some support for these technologies on Windows 7, but it is limited.

I was primarily referring to Windows 8/8.1, which is still (supposedly) fully supported.

> The cost of creating modern software on legacy platforms goes up every year while the benefits go down.

As a developer myself, I respectfully disagree. Once the code base is built, there's no issue of backward compatibility, and prematurely abandoning releases is a huge disservice to users, who may have good reasons for not upgrading.

> I don’t blame them for only targeting modern versions of Windows.

I do. Like the artificial Intel processor restrictions, I think it's quite clear the real reason is to force users onto Windows 10 for purposes of control and monetization, and I have no wish to go there. _I choose what to run on my computer._ The "modern" claim is spin—the vast majority of Windows is still Windows.

> Have you tried WSL2 support in Windows 10? Running Ubuntu natively inside of Windows 10 is a dream come true—no VMs, containers, or software layers (like MinGW), just a Linux kernel running side-by-side with the Windows kernel.

WSL 2 is Linux on Windows in a virtual machine, just lighter weight. I'm happy running Linux (Mint) under Hyper-V for the occasional Linux task. (I also use Hyper-V for other Windows versions and for Android development.) When I need to get serious, I boot Linux alone (and that's happening more and more as I prepare for the eventual need to transition away from Windows).

**Comment by JNavas2** [comment]
p.s. For what it's worth, I normally run Windows 8.1 Pro on a Kaby Lake processor by means of the hack that disables the (offensive) CPU version block. Kaby Lake, after all, is essentially just a Skylake refresh. I'd still be running Windows 7 but for the ending of support, which makes it an unacceptable risk given the many Windows security issues.

**Comment by RespectIsEverything** [comment]
Many thanks. Your work is very much appreciated here.

Glad to see it will gain more exposure with PowerToys.
The people do not know what they've been missing.

Quite a shame MS never incorporated this code into the OS itself.

But unsurprising from the company whose OS requires 3rd party SW (7+ Taskbar Tweaker) to reduce the width of a vertical taskbar. Really helps your workflow having the taskbar in the vertical position, particularly on the right. Reducing the width enhances screen real estate.

Grateful salutations Brice :)

**Comment by JNavas2** [comment]
> Really helps your workflow having the taskbar in the vertical position, particularly on the right. Reducing the width enhances screen real estate.

Auto-hide the taskbar (in Properties), and you lose zero screen real estate no matter where the taskbar is located. My own preference (with auto-hide) is still the bottom.
